set(CMAKE_Fortran_COMPILER "gfortran-9")
set(GMSH_ROOT "/opt/uliege/gmsh")
set(MUMPS_ROOT "/usr/local/Cellar/brewsci-mumps/5.3.5")
set(MKL_ROOT "/opt/intel")
set(MATHGL_ROOT "/Users/matteo/mroot/mathgl")